---
title: "CV: Garrett Olson Stanford"
---

[PDF](cv/CV-8-10-23.pdf)
<br><br>

## <u>Academic Positions</u>

Postodoctoral Associate, University of Georgia, 2023--present

## <u>Education</u>
B.A. Japanese, University of Puget Sound, 2014
<br> B.S. Economics, University of Puget Sound, 2014
<br> M.S. Economics, University of Oregon, 2018
<br> Ph.D. Economics, University of Oregon, 2023

- *Fields:* Public Economics, Environmental Economics, Experimental Economics, Economics of Crime and Policing
- *Committee:* [Edward A. Rubin](https://edrub.in/), [Trudy Ann Cameron](https://pages.uoregon.edu/cameron/vita/), [Jonathan M.V. Davis](https://sites.google.com/site/jonathanmvdavis/)

<br><br>


## <u>Research</u>
<br>

### Working Papers: 

[Police are less likely to respond to requests for help from minorities: Field experiment evidence of police discrimination](papers/Stanford_police_1-25-23.pdf)


<br>

[Public preferences for a state-level carbon cap-and-trade program](papers/Stanford_Cameron_8-9-23.pdf) 
<br> with Trudy Ann Cameron



<br>

[Gun control and the steel paradox](papers/OreGUNians_8-9-23)
<br> with Katie Bollman, Benjamin Hansen and Edward Rubin

<br>

### Research in progress:

**Asset Forfeitures and Traffic Fines: Substitutes or Complements?**


**Distributional Impacts of Gun-control Laws**
<br> with Tami Ren

**Using Machine Learning to Explore Racist Stereotypes**
<br> with Edward Rubin

<br><br>

## <u>Teaching Experience</u>
<br>

### Sole Instructor
[EC 201: Introduction to Microeconomics:](teaching/201_syllabus.pdf) _Fall 2020, Winter 2022, Summer 2022_

[EC 333: Natural Resources & Environmental Issues:](teaching/333_syllabus.pdf) _Summer 2021, Spring 2022_

<br>

### Teaching Assistant


#### **Graduate Level:**
- **EC 510: Big Data in Economics:** _Spring 2020, Spring 2021_
- **EC 525: Advanced Econometrics:** _Spring 2020_
- **EC 535: Natural Resource Economics:** _Spring 2019_
- **EC 551: Labor Econ Issues** _Spring 2020_
<br>

#### **Undergraduate Level:**	      
- **EC 419: Analysis of Community Issues:** _Spring 2021_
- **EC 421: Introduction to Econometrics:** _Winter 2020_
- **EC 333: Natural Resources & Environmental Issues:** _Fall 2022, Spring 2023_
- **EC 201: Introduction to Microeconomics:** _Spring 2019, Fall 2019_
- **EC 202: Introduction to Macroeconomics:** _Winter 2019, Winter 2021_
- **EC 311: Intermediate Microeconomics:** _Fall 2019, Fall 2022, Spring 2023_
- **EC 101: Introduction to Economics:** _Fall 2018_
<br><br>


## <u>Conference and Seminar Presentations</u> 

 Western Economic Association International (WEAI) Annual Conference *(2022)*
<br> Association of Environmental and Resources Economists (AERE) Annual Summer Conference *(2022)*
<br> Society for Benefit Cost Analysis (SBCA) Annual Conference _(2022)_
<br> University of Oregon Microeconomics group _(2021, 2022)_
<br> Berkeley/Sloan Summer School in Environmental and Energy Economics _(2020)_
<br>JET Skills and Development Conference _(2016)_
<br> European Writing Center Association Conference _(2014)_
<br><br>

## <u>Honors and Awards</u> 
Graduate Teaching Fellowship _2018 - 2023_
<br> Edward G. Daniel Scholarship _2019_
<br> Robert G. Albertson Award _2014_
<br>	Phi Beta Kappa Honor Society _2014_
	
