---
title: "Teaching"
---

I have worked as an educator in various capacities for the last ten years. Please see my [teaching statement](teaching/Final Teaching Statement.pdf) for an overview of my teaching philosophy and experience as an educator. 

<br>

At the University of Oregon, I am a **lead instructor** for undergraduate courses on environmental economics and introductory microeconomics:

- [EC 201: Introduction to Microeconomics:](teaching/201_syllabus.pdf)
- [EC 333: Natural Resources & Environmental Issues:](teaching/333_syllabus.pdf)

<br>

I have served as a **teaching assistant** for a wide range of economics courses at both the graduate and undergraduate level. My roles have involved assisting honor students develop independent research projects and teaching **R** lab sessions for econometrics. 

- [EC 421: Introduction to Econometrics](https://github.com/GarrettStanford21/421_Winter_2020/blob/master/README.md)

<br>

## Selected Student Evaluations

Full student evaluations are availble upon request.

<u>**As a lead instructor:**</u>

- "Garrett you are an awesome guy and made the class a whole lot more fun. Favorite teacher I have had in the Econ department and you deserve recognition for that!"

- "Lectures were always very distinct and memorable, with no two lectures feeling too similar in topic. The way the assignments on canvas were posted always allowed for ample preparation in advance, and slides were always posted shortly after their corresponding lecture."

- "I appreciate you, Garrett! Keep being you and being a great guy!"

- "Garrett answered all of my questions and he had an obvious, deep understanding of what he was talking about."

- "None of the elements need improvement...overall great class"

- "Professor Stanford did a great job and made the lectures very engaging, especially for an online setting."

- "I feel the instructor was very supportive and did not want any of his students to fail. He was very easy to talk to, and he made the course very entertaining while I still learned a lot."

- "Garrett was awesome, deserves a raise or more praise. Definitely do something to reward that behavior."

<br>

<u> **As a teaching assistant:**</u>

- "He was informative, patient, and explained concepts/examples in ways that were applicable and easy to understand."	

- "Garrett Stanford was a great discussion leader. Stanford was well versed, organized and engaging in regards to the material. Stanford was quick to respond to emails, held accessible and helpful office hours and was always willing to help and explain as much as possible."

- "He was very good at making complicated economic concepts more accessible and easy to understand. He was also good at answering people's questions."	

- "Garrett Stanford lead the discussion classes very well. Stanford encouraged our participation as well as explain all material thoroughly. The discussion material was helpful and prepared us for the tests well."

- "Garrett has been an excellent discussion leader, for a few reasons. First of all, he teaches with a sense of humility that you can tell right of that bat. He's there because he wants us to learn more, and that makes a massive difference towards the effectiveness of the discussion. Second, Garrett was always prepared to answer questions, and was able to pose these answers in a way we could all understand, making things simple while still keeping all the content. Overall, Garrett has been a personal favorite and has shown a capacity to be a strong leader and teacher."

- "Stanford was great. He was obviously passionate and invested. I always enjoyed my time in discussion."	




 


